### ISSUE TITLE
Orange Pi Zero

### ISSUE THREAD

**Issue by mindw00rk** [znoxx/torbox#1]
Здравствуйте, как насчет поддержки Orange Pi Zero в проекте?

**Comment by znoxx** [comment]
Да, закажу в начале декабря.
Скорее всего вначале будет "костыль" с ручной установкой, ибо Armbian.
Потом будет глобальный переход на armbian. 
Оптимистичный прогноз - конец января, начало февраля. Реальный - весна 2017.
Там много задумок и скорее всего будем переписывать всё from scratch.

**Comment by znoxx** [comment]
Orange Pi Zero поддержан
